### ISSUE TITLE
Stop Working  with SSL  error

### ISSUE THREAD

**Issue by fernac03** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#32]
integration stop with 
Error requesting FusionSolarKiosk data: HTTPSConnectionPool(host='intl.fusionsolar.huawei.com', port=443): Max retries exceeded with url:  (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by tijsverkoyen** [comment]
What is your kiosk url? Does this show a certificate error also?
My first guess would be your kiosk url is not correct.

**Comment by Bernkastel-0** [comment]
Same issue:

Error requesting FusionSolarKiosk data: HTTPSConnectionPool(host='intl.fusionsolar.huawei.com', port=443): Max retries exceeded with url: /rest/pvms/web/kiosk/v1/station-kiosk-file?kk=[HIDDEN] (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

Attempting to access that URL via PC browser has no issues.

**Comment by tijsverkoyen** [comment]
Do you have access to the machine where your Home Assistant is running on? If so: can you try
`curl -I https://intl.fusionsolar.huawei.com`. If this throws an error I think your system is outdated.

**Comment by Bernkastel-0** [comment]
Thanks tijsverkoyen, that led me down the right track. curl indeed did not work as the SSL intermediate certificate for "Actalis Organization Validated Server CA G3" was not available, even with `sudo update-ca-certificates -f`

Manually adding that certificate to HA python certifi package fixed the issue
