### ISSUE TITLE
schedule the request

### ISSUE THREAD

**Issue by fmarton** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#39]
Hi, 

Home assistant scheduled the request some minutes after the hour (twice an hour). So the energy panel calculates the produced energy based on almost 30minutes earlier value. 
How can I set the schedule that the srequest be in every hour 58mins?

Thanks
Ferenc

**Comment by tijsverkoyen** [comment]
I don't know which request you mean, because the interval the data is fetched from the Kiosk API is every [300](https://github.com/tijsverkoyen/Home-Assistant-FusionSolar-Kiosk/blob/master/custom_components/fusion_solar_kiosk/sensor.py#L52) seconds (5 minutes).

**Comment by fmarton** [comment]
![image](https://user-images.githubusercontent.com/21972520/194905063-ebfa7101-c7e0-4ee7-818a-ece50d97d960.png)

Mine is 30mins! I dont know why.

**Comment by tijsverkoyen** [comment]
Can you check if the value is 300 in custom_components/fusion_solar_kiosk/sensor.py at line L52?
If not can you [enable debugging](https://www.home-assistant.io/integrations/logger/#log-filters) and check if there are entries every 300 seconds?

**Comment by tijsverkoyen** [comment]
I think something has changed on the end of FusionSolar. I think they only update the realtime value per 30min in the Kiosk:

> After the Kiosk view is generated, the plant running data is refreshed every 30 minutes. You can refresh the browser to obtain the latest data,

Source: https://region04eu5.fusionsolar.huawei.com/hedex/hedex.do?lib=monitoring&pidid=pid_neteco_monitoring&topicid=share_plan_owner&locale=en-us&hdxsrc=original&keyword=kiosk

**Comment by arboeh** [comment]
I can confirm that data is updated every 30 min now. Is that chinese "realtime data"?  &#x1F648;

**Comment by tijsverkoyen** [comment]
I don't think there will be much I can do about it. The response from the API with the data seems to be same for 30 minutes. 
When I compare the kiosk view with the web interface the kiosk keeps showing "old" data, even when refreshing manually.

**Comment by arboeh** [comment]
Huawei... No words for that. Hopefully they enable Modbus TCP for me soon, because I need realtime data for charging my ev...
Anyway, you did a great job with this integration.

**Comment by olibos** [comment]
Hello, 

Since I've started with Kiosk a month ago, it seems that data has a 30 minutes cache at Huawei server side.
You can see that when you go to the kiosk page. The data is freezed for 30 minutes as well.

On my side to avoid that cache delay, I've made my first integration, thanks to @tijsverkoyen's work!
That integration use the OpenApi supplied by Huawei.
Here is an example from yesterday comparing the data from both integrations:
![image](https://user-images.githubusercontent.com/6031263/195543909-e38a7cda-eec6-4f6b-87f2-1923c00fac9b.png)
(blue: OpenApi purple: Kiosk)

Integration: https://github.com/olibos/Home-Assistant-FusionSolar-OpenApi/
@tijsverkoyen I've added some credits [here](https://github.com/olibos/Home-Assistant-FusionSolar-OpenApi/#credits), let me know if it's ok for you

**Comment by tijsverkoyen** [comment]
@olibos that's fine by me. I was thinking to extend my integration with OpenApi, so one can choose

**Comment by tijsverkoyen** [comment]
I have added a link to your repo in the README.md
