### ISSUE TITLE
 No Kiosk data.

### ISSUE THREAD

**Issue by AndersHoglund** [tijsverkoyen/Home-Assistant-FusionSolar-Kiosk#41]
This morning, no Kiosk data visible. Blank energy page. Log said:

```
This error originated from a custom integration.

Logger: custom_components.fusion_solar_kiosk.sensor
Source: helpers/update_coordinator.py:151
Integration: FusionSolar Kiosk (documentation, issues)
First occurred: October 14, 2022 at 22:12:03 (2 occurrences)
Last logged: 01:42:03

Error requesting FusionSolarKiosk data: Expecting value: line 1 column 1 (char 0)
Error requesting FusionSolarKiosk data: HTTPSConnectionPool(host='region02eu5.fusionsolar.huawei.com', port=443): Max retries exceeded with url: /rest/pvms/web/kiosk/v1/station-kiosk-file?kk=q9KgDdcj4L (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8b097ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

Tried to restart HA, did not help. Only a couple of new log entries:
```
This error originated from a custom integration.

Logger: custom_components.fusion_solar_kiosk.fusion_solar_kiosk_api
Source: custom_components/fusion_solar_kiosk/fusion_solar_kiosk_api.py:46
Integration: FusionSolar Kiosk (documentation, issues)
First occurred: 12:08:50 (3 occurrences)
Last logged: 12:18:50

Retrieving the data failed with failCode: 0, data: neteco.pvms.systemSetting.notExists
```
And:

```
Logger: homeassistant.components.sensor
Source: custom_components/fusion_solar_kiosk/__init__.py:139
Integration: Sensor (documentation, issues)
First occurred: 12:08:50 (2 occurrences)
Last logged: 12:08:50

Error adding entities for domain sensor with platform fusion_solar_kiosk
Error while setting up fusion_solar_kiosk platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 139, in state
    return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'realTimePower'

```

I  think all this boils down to a problem in the Huawei end. But maybe we need to handle for example "Max Retries" etc in some way. How I do not know. Wish I could do an installer login and enable local MODBUS/TCP, getting rid of this cloud dependency.
/A

**Comment by AndersHoglund** [comment]
It is definitely a Huawei issue. Running the Kiosk url in a browser yields this response:
`{"data":"neteco.pvms.systemSetting.notExists","success":false,"failCode":0} `

/A

**Comment by J3susTheChosenOne** [comment]
They had an update on the Fusion solar server from Oct14 22:00 - Oct 15  10:00 (UTC+2) according to their anouncement in the mobile app.I think they maybe changed something from theire end, since then my config also does not work (HA, HACS, everything up to date, running on HAOS )

I get the following error now, maybe it could be related:

Logger: homeassistant
Source: custom_components/fusion_solar_kiosk/__init__.py:139
Integration: FusionSolar Kiosk ([documentation](https://github.com/tijsverkoyen/Home-Assisant-FusionSolar-Kiosk), [issues](https://github.com/tijsverkoyen/Home-Assisant-FusionSolar-Kiosk/issues))
First occurred: 9:49:34 PM (2 occurrences)
Last logged: 9:54:34 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 139, in state
    return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'realTimePower'

**Comment by Zkaning** [comment]
I was able to create a new kiosk at the FusionSolar website and got a new Url. It’s working in HA again now. Hope it will sustain, I did it just 5min ago…

**Comment by AndersHoglund** [comment]
Yes. Creating a new kiosk resolved the issue. 
I can not find out how to remove the old energy entity in the Energy dashboard. You can delete a working entity, but not a dead one.

**Comment by J3susTheChosenOne** [comment]
Can confirm, with the new link does work for me to, but i had to remove the integration, reboot the host, and reinstall the integration for it to work. Before doing so, i just got a timeout.

**Comment by eternum79** [comment]
> Can confirm, with the new link does work for me to, but i had to remove the integration, reboot the host, and reinstall the integration for it to work. Before doing so, i just got a timeout.

I have followed this advice but the entities continue to be unavailable

**Comment by leeyuentuen** [comment]
seems the key of the kiosk is changed
I can from this
https://region04eu5.fusionsolar.huawei.com/pvmswebsite/nologin/assets/build/index.html#/kiosk?kk=eJQxxxxxxO
to
https://region04eu5.fusionsolar.huawei.com/pvmswebsite/nologin/assets/build/index.html#/kiosk?kk=Ey7tFd4dnvxbE5zxxxxxxxMCJOtf329hg

(change a little bit with x) but the length of the kk key is longer

**Comment by tijsverkoyen** [comment]
As @J3susTheChosenOne commented. Huawei Fusion Solar got an update which seems to reset all Kiosk urls. Mine was also reset. The `kk` parameter is also much longer.

**An important remark: I will no longer maintain this custom integration.** I have create the newer [FusionSolar](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar)-integration, which has a visual flow to configure when you install the integration, and also has support for using an OpenAPI account instead of the kiosk mode.

Therefore I strongly suggest that you upgrade to the newer [FusionSolar](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar)-integration.
